# Generated by Django 4.0.8 on 2023-04-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        ('baskets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productslist',
            name='producer_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list', to='cells.producercell'),
        ),
        migrations.AddField(
            model_name='monthcycle',
            name='producer_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_cycles', to='cells.producercell'),
        ),
        migrations.AddField(
            model_name='basket',
            name='consumer_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cells.consumercell'),
        ),
        migrations.AddField(
            model_name='basket',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='week_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='baskets.weekcycle'),
        ),
    ]
