# Generated by Django 4.0.8 on 2023-05-31 21:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_unit_k_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclesettings',
            name='week_day_requests_end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekcycle',
            name='request_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
