# Generated by Django 4.0.8 on 2023-06-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_cyclesettings_week_day_requests_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekcycle',
            name='request_day',
            field=models.DateTimeField(),
        ),
    ]
