image: docker:stable

stages:
  - build
  - portainer

.build_meta: &build_template
  stage: build
  script:
    - docker build -f compose/production/django/Dockerfile -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" --no-cache .
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER  -p $CI_REGISTRY_PASSWORD
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

build_staging:
  <<: *build_template
  only:
    - staging
  variables:
    IMAGE_TAG: staging

build_production:
  <<: *build_template
  only:
    - main
  variables:
    IMAGE_TAG: latest


#### DEPLOY
#
# Exige configuração no PORTAINER e GITLAB 
#
# WEBHOOK_PORTAINER: Possui a URL para rebootar o Serviço em produção
# URL de Webhook será enviada pela SeTIC mediante requisição via chamado.
# Esta variável deve ser configurada no codigos.ufsc.br:
# Dentro do projeto > Settings > CI/CD > Secret Variables

.portainer_meta: &portainer_template
  stage: portainer
  image: alpine:latest
  script:
    - if [[ ! -z "${WEBHOOK_PORTAINER}" ]]; then
        for i in $(echo ${WEBHOOK_PORTAINER} | sed "s/,/ /g"); do wget --post-data '' -O - "$i"; done
      else
        echo "Empty \$WEBHOOK_PORTAINER" ; exit 1;
      fi

portainer_staging:
  <<: *portainer_template
  only:
    - staging
  variables:
    WEBHOOK_PORTAINER: ${WEBHOOK_PORTAINER_STAGING}

portainer_production:
  <<: *portainer_template
  only:
    - main
  variables:
    WEBHOOK_PORTAINER: ${WEBHOOK_PORTAINER_PRODUCTION}