# Generated by Django 4.0.8 on 2022-11-09 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cells.role'),
        ),
        migrations.AddField(
            model_name='celllocation',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cells.cell'),
        ),
        migrations.AddField(
            model_name='cell',
            name='members',
            field=models.ManyToManyField(through='cells.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='application_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cells.applicationsurvey'),
        ),
        migrations.AddField(
            model_name='applicationanswer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='cells.application'),
        ),
        migrations.AddField(
            model_name='applicationanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cells.applicationquestion'),
        ),
        migrations.AddField(
            model_name='application',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cells.cell'),
        ),
        migrations.AddField(
            model_name='application',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
