# Generated by Django 4.0.8 on 2023-03-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllocation',
            name='neighborhood',
            field=models.CharField(default='Centro', max_length=50),
            preserve_default=False,
        ),
    ]
