# Generated by Django 4.0.8 on 2023-10-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_consumercell_message_group_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercell',
            name='share_day',
            field=models.CharField(default='Quinta-feira', max_length=15),
        ),
    ]
