# Generated by Django 4.0.8 on 2023-03-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_celllocation_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='person',
        ),
    ]
